### ISSUE TITLE
Enhancement: Added icons for candidates

### ISSUE THREAD

**Issue by krisfans** [Shougo/ddc-nvim-lsp#17]
Enhancement: Added icons for candidates like deoplete https://github.com/deoplete-plugins/deoplete-lsp/blob/master/rplugin/python3/deoplete/source/lsp.py#L40

**Comment by Shougo** [comment]
Sorry.  I don't add the feature.  But you can set icon by `kindLabels`.
https://github.com/Shougo/ddc-nvim-lsp/blob/main/doc/ddc-nvim-lsp.txt#L55
